Implement `bin/style` and `bin/lint` scripts
This implements the commands documented in a previous update to the
CONTRIBUTING.md document. The commands are currently implemented as fish
scripts since they are derived from the equivalent scripts I wrote for
the Fish shell project. TODO is rewriting them as ksh scripts.

diff --git a/bin/lint b/bin/lint
--- a/bin/lint
+++ b/bin/lint
@@ -1,66 +1,56 @@
 #!/usr/bin/env fish
 #
-# Usage: bin/lint [--all] [source_filename]...
+# Usage: bin/lint [--all] [directory_or_filename]...
 #
-# Run the source through various lint detection tools. If invoked with one or more path names they
-# will be linted. Otherwise any uncommitted source files are linted. If there is no uncommitted
-# change then the files in the most recent commit are linted.
+# Run the source through various lint detection tools. If invoked with `-all` then all the
+# src/cmd/ksh93 source files will be linted. If invoked with one or more path names they
+# will be linted. If the pathname is a directory all *.c files inside it will be linted.
+# Otherwise any uncommitted source files are linted. If there is no uncommitted change
+# then the files in the most recent commit are linted.
 #
+set all no
 set cppchecks warning,performance,portability,information,missingInclude
-set cppcheck_args
+set enable_global_analysis
+set lint_args
 set c_files
 set files
-set all no
 set kernel_name (uname -s)
 set machine_type (uname -m)
 
-set -gx CXX $argv[1]
-set -e argv[1]
+if not test -d build
+or not test -f build/compile_commands.json
+    echo "You need to run `meson` to configure the build before we can lint the source." >&2
+    exit 1
+end
 
-if test "$argv[1]" = "--all"
-    set all yes
-    set cppchecks "$cppchecks,unusedFunction"
-    set -e argv[1]
-    if set -q argv[1]
-        echo "Unexpected arguments: '$argv'" >&2
-        exit 1
+# Deal with any CLI flags.
+while set -q argv[1]
+    if test "$argv[1]" = "--all"
+        set all yes
+        set -e argv[1]
+    else
+        break
     end
-else
-    set files $argv
-end
-
-if test $kernel_name = Linux
-    # This is an awful hack. However, the include-what-you-use program spews lots of errors like
-    #   /usr/include/unistd.h:226:10: fatal error: 'stddef.h' file not found
-    # if we don't explicitly tell it where to find the system headers on Linux. See
-    # http://stackoverflow.com/questions/19642590/libtooling-cant-find-stddef-h-nor-other-headers/
-    set -l sys_includes (eval $CXX -v -c src/builtin.cpp 2>&1 | \
-        sed -n -e '/^#include <...> search/,/^End of search list/s/^ *//p')[2..-2]
-    set -x CPLUS_INCLUDE_PATH (string join ':' $sys_includes)
-end
-
-# We only want -D and -I options to be passed thru to cppcheck.
-for arg in $argv
-    if string match -q -- '-D*' $arg
-        set cppcheck_args $cppcheck_args $arg
-    else if string match -q -- '-I*' $arg
-        set cppcheck_args $cppcheck_args $arg
-    else if string match -q -- '-iquote*' $arg
-        set cppcheck_args $cppcheck_args $arg
-    end
-end
-
-# Not sure when this became necessary but without these flags cppcheck no longer works on macOS.
-# It complains that "Cppcheck cannot find all the include files." Adding these include paths should
-# be harmless everywhere else.
-set cppcheck_args $cppcheck_args -I /usr/include -I .
-
-if test "$machine_type" = "x86_64"
-    set cppcheck_args -D__x86_64__ -D__LP64__ $cppcheck_args
 end
 
 if test $all = yes
-    set files src/**.c
+and set -q argv[1]
+    echo "Unexpected arguments: '$argv'" >&2
+    exit 1
+end
+
+# Figure out which files to lint.
+if test $all = yes
+    set files src/cmd/ksh93/**.c
+else if set -q argv[1]
+    set files
+    for f in $argv
+        if test -f $argv
+            set files $files $f
+        else if test -d $argv
+            set files $files {$argv}**.c
+        end
+    end
 else
     # We haven't been asked to lint all the source or specific files. If there are uncommitted
     # changes lint those, else lint the files in the most recent commit.
@@ -73,20 +63,50 @@ else
     end
 end
 
-# Extract just the C files that exist.
-for file in (string match -r '^.*\.(?:c|h)$' -- $files)
+# Filter out non C source files.
+set c_files
+for file in (string match -r '^.*\.c$' -- $files)
     if test -f $file
-        set c_files $c_files $file
+        set c_files $c_files ../$file
     end
 end
 
-# We now have a list of files to check so run the linters.
+cd build
+
+# We need to limit the source modules to those for which we have build rules. We also need to
+# produce a version of the compile_commands.json file that only contains the files to be linted.
+# Finally, we need the `-D` and `-I` flags from the build rule for the IWYU and cppcheck programs.
+set project_file compile_commands_partial.json
+set defs_file cppcheck_defs
+set c_files (../bin/partition_compile_db compile_commands.json $project_file $defs_file \
+             $c_files)
 if not set -q c_files[1]
-    echo
-    echo 'WARNING: No C/C++ files to check'
-    echo
+    echo >&2
+    echo 'WARNING: No C files to check' >&2
+    echo >&2
     exit 1
 end
+
+# On some platforms (e.g., macOS) oclint can't find the system headers. So ask the real compiler
+# to tell us where they are and pass that information to oclint.
+#
+# Passing this path via the compiler `-isystem` flag also keeps oclint from complaining about
+# problems with the system headers.
+#
+# We also need this value for cppcheck to find some system headers again, on platforms like macOS,
+# where the system headers aren't found at /usr/include.
+set system_hdrs (clang -H -E ../bin/hdrs.c 2>&1 | head -1 | sed -e 's/^\. //' -e 's/\/[^/]*$//')
+
+# On macOS the system headers used by `clang` may not be rooted at /usr/include.
+set lint_args $lint_args -I$system_hdrs
+
+# This is needed with clang on macOS. Without it `cppcheck` fails with
+# `#error Unsupported architecture` from `#include <sys/cdefs.h>`.
+if test "$machine_type" = "x86_64"
+    set lint_args $lint_args -D__x86_64__ -D__LP64__
+end
+
+set lint_args $lint_args (cat $defs_file)
 
 if type -q include-what-you-use
     echo
@@ -94,17 +114,9 @@ if type -q include-what-you-use
     echo Running IWYU
     echo ========================================
     for c_file in $c_files
-        switch $kernel_name
-            case Darwin FreeBSD
-                include-what-you-use -Xiwyu --no_default_mappings -Xiwyu \
-                    --mapping_file=build_tools/iwyu.osx.imp --std=c++11 \
-                    $cppcheck_args $c_file 2>&1
-            case Linux
-                include-what-you-use -Xiwyu --mapping_file=build_tools/iwyu.linux.imp \
-                    $cppcheck_args $c_file 2>&1
-            case '*' # hope for the best
-                include-what-you-use --std=c++11 $cppcheck_args $c_file 2>&1
-        end
+        include-what-you-use -Xiwyu --transitive_includes_only --std=c99 \
+            -Wno-expansion-to-defined -Wno-nullability-completeness \
+            $lint_args $c_file 2>&1
     end
 end
 
@@ -116,15 +128,19 @@ if type -q cppcheck
     # The stderr to stdout redirection is because cppcheck, incorrectly IMHO, writes its
     # diagnostic messages to stderr. Anyone running this who wants to capture its output will
     # expect those messages to be written to stdout.
-    set -l cn (set_color normal)
+    set -l cn (set_color normal | string trim --chars \cO)
     set -l cb (set_color --bold)
     set -l cu (set_color --underline)
     set -l cm (set_color magenta)
     set -l cbrm (set_color brmagenta)
     set -l template "[$cb$cu{file}$cn$cb:{line}$cn] $cbrm{severity}$cm ({id}):$cn\n {message}"
-    set cppcheck_args -q --verbose --std=c++11 --std=posix --language=c++ --template $template \
-        --suppress=missingIncludeSystem --inline-suppr --enable=$cppchecks \
-        --rule-file=.cppcheck.rules --suppressions-list=.cppcheck.suppressions $cppcheck_args
+
+    # It should be possible to use --project=$project_file but cppcheck 1.82 doesn't correctly
+    # extract the -D and -I flags. So we do it ourselves and pass the flags on the cppcheck
+    # command line.
+    set cppcheck_args $lint_args -q --verbose --std=c99 --std=posix --language=c \
+        --template $template --suppress=missingIncludeSystem --inline-suppr --enable=$cppchecks \
+        --rule-file=../.cppcheck.rules --suppressions-list=../.cppcheck.suppressions
 
     cppcheck $cppcheck_args $c_files 2>&1
 
@@ -142,27 +158,10 @@ if type -q oclint
     echo ========================================
     echo Running oclint
     echo ========================================
-    # The stderr to stdout redirection is because oclint, incorrectly writes its final summary
-    # counts of the errors detected to stderr. Anyone running this who wants to capture its
-    # output will expect those messages to be written to stdout.
-    if test "$kernel_name" = "Darwin"
-        if not test -f compile_commands.json
-            xcodebuild -alltargets >xcodebuild.log
-            oclint-xcodebuild xcodebuild.log >/dev/null
-        end
-        if test $all = yes
-            oclint-json-compilation-database -e '/pcre2-10.22/' -- -enable-global-analysis 2>&1
-        else
-            set i_files
-            for f in $c_files
-                set i_files $i_files -i $f
-            end
-            echo oclint-json-compilation-database -e '/pcre2-10.22/' $i_files
-            oclint-json-compilation-database -e '/pcre2-10.22/' $i_files 2>&1
-        end
-    else
-        # Presumably we're on Linux or other platform not requiring special
-        # handling for oclint to work.
-        oclint $c_files -- $argv 2>&1
-    end
+    # A copy of this config file has to be in the CWD (the Meson build dir).
+    test -f .ocling
+    or cp ../.oclint .
+
+    oclint -p $PWD -enable-clang-static-analyzer $enable_global_analysis \
+        -extra-arg="-isystem" -extra-arg="$system_hdrs" $c_files
 end
